### ISSUE TITLE
Imagenet Model Zoo

### ISSUE THREAD

**Issue by Param-Raval** [Horizon2333/imagenet-autoencoder#3]
Hello!

Thank you for this great project implementation. I was wondering if you'd now have some of the other pretrained weights for Imagenet? If so, could you please share?

Secondly, could you also tell me some of the training details for Imagenet like how long it took, the hardware specs, total dataset size, etc. Anything I should know before I attempt to train it myself.

Thanks again.

**Comment by Horizon2333** [comment]
Hi,

Thank you for the interest. 

I'm so sorry due to the device limitation (since I do not have access to use previous gpu cluster anymore) that I cannot provide more pretrained models. But I do have something more, they are models pretrained from Objects365, an object detection dataset which is about half of the size of ImageNet. I have uploaded them. Though the size of both dataset is close, it may be some gaps and I do not have any insight about this.

For your second question,  I just use the default hyper parameters to train models from any image datasets, that may be not reasonable but I do not have resources to do hyper-parameter optimization at that time. For the training time, please wait several hours and I need to find the previous logs etc then I can give you the answer.

All the best.

**Comment by Param-Raval** [comment]
Thank you for adding the new weights! But I'm afraid you'll have to change the permissions to allow anyone to access them.

**Comment by Horizon2333** [comment]
That's fine now. So sorry about this.

**Comment by Param-Raval** [comment]
Thanks 👍 

Whenever possible, could you please tell us the hardware specs on which you trained these models? I'm running out of memory on Colab training this on Imagenet. Thanks.

**Comment by Horizon2333** [comment]
Train this model in a single card is difficult. I use a cluster with 8 1080Ti at that time.

**Comment by Param-Raval** [comment]
I see. Noted.

Kindly share the log file if you can. And thank you for your help.

**Comment by Horizon2333** [comment]
Hi

I'm sorry to reply so late. I tried to find the previous logs, but unfortunately, they were lost, even if I asked my former colleagues. But I asked someone else to try to run my code. For the Objects365 dataset, when training VGG16 with 8 1080Ti, an epoch takes about 40 minutes. It can be inferred that for ImageNet, the time consumption of an epoch is about an hour and a half. Considering that a total of 100 epochs are required, the Objects365 dataset takes about 3 days and the ImageNet dataset takes about a week. In addition, the training time of ResNet50 can be reduced by 40% compared with VGG16.

Best wishes
