### ISSUE TITLE
The problem of using autoencoder on Imagenet

### ISSUE THREAD

**Issue by 20000yshust** [Horizon2333/imagenet-autoencoder#5]
Hello! I download the imagenet-vgg16.pth in the model zoo and try to load it into the vggautoencoder you have created, but it has errors——Unexpected key(s) in state_dict: "module.encoder.conv1.0 EncoderLayer.layer.0.weight"...， how can I solve this problem?

**Comment by Horizon2333** [comment]
Hi, do you use the build function in models/builder.py? Maybe the error comes from that you do not use 'DataParallel' or 'DistributedDataParallel' to modify the model and these two operations will add 'module' in the keys of model weights. So if you do not add these two operations, the keys of model weights will be 'encoder.conv1.0 EncoderLayer.layer.0.weight' rather than 'module.encoder.conv1.0 EncoderLayer.layer.0.weight'. Hope this is the reason of the error. If it doesn't work, you can further contact with me.

**Comment by 20000yshust** [comment]
Yes, the reason is the "module" in the keys and I have already solved this problem, thanks!

**Comment by Horizon2333** [comment]
I'm glad your problem has been solved. 
Hope the code is helpful.
